name: Monthly charges deduction

on:
  schedule:
    - cron: '*/1 * * * *' # Runs on the 1st day of every month at 00:00 UTC

jobs:
  run-api:
    runs-on: ubuntu-latest
    push:
      branches:
        - vdg_monthly_deduction_automation

    steps:
      - name: Run Monthly charges deduction API
        run: |
          export TOKEN=$TOKEN_SECRET
          curl -H "Authorization: Bearer $TOKEN" http://192.168.29.116:8090/api/v1/open/cities
        env:
          TOKEN_SECRET: ${{ secrets.API_TOKEN }}