name: Monthly charges deduction

on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *' # Runs on the 1st day of every month at 00:00 UTC

jobs:
  run-api:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run Monthly charges deduction API
        run: |
          curl -I http://192.168.29.116:8090/api/v1/open/cities
