name: Scheduled URL Test

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every minute

jobs:
  test-url:
    runs-on: ubuntu-latest

    steps:
      - name: Test URL
        run: |
          curl -I http://192.168.29.116:8090/
