name: Scheduled URL Test

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every minute

jobs:
  test-url:
    runs-on: ubuntu-latest

    steps:
      - name: Test URL
        run: |
          curl https://87e8-2405-201-d003-1bdd-f58c-c195-7aa2-56a1.ngrok-free.app/api/v1/open/cities
