name: Scheduled URL Test

on:
  workflow_dispatch:
    - cron: '*/1 * * * *' # Runs every minute
  push:
    branches:
      - main

jobs:
  test-url:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test URL
        run: |
          curl https://webhook.site/e8f22772-d7d6-4ef4-9324-aea57abfc879
